#!/bin/bash

#Scrip for everything Travis CI

set -o nounset
set -o xtrace

./autogen.sh
CFLAGS="-O0 -Wall -Wextra --coverage" ./configure --with-pic

make -C doc doc
make



# NOTES:

# Coverage data matches the source files more closely if you do not optimize.

# --coverage
# This option is used to compile and link code instrumented for coverage analysis. The option is
# a synonym for -fprofile-arcs -ftest-coverage (when compiling) and -lgcov (when linking).