#!/bin/sh

(cd /usr/local/stow && sudo stow -D libnet)
find /usr/local -name libnet\* | grep -v /usr/local/stow/libnet
sudo rm -rf /usr/local/stow/libnet
sudo mkdir -p /usr/local/stow/libnet
sudo make install prefix=/usr/local/stow/libnet
(cd /usr/local/stow && sudo stow -v libnet)

