#!/usr/bin/env lua

require"nfct"

ct=assert(nfct.new())

assert(ct == nfct.set_attr_ipv4(ct, "orig-ipv4-src", "1.2.3.4"))
assert("1.2.3.4" == nfct.get_attr_ipv4(ct, "orig-ipv4-src"), nfct.get_attr_ipv4(ct, "orig-ipv4-src"))
assert("number" == type(nfct.get_attr_u32(ct, "orig-ipv4-src")))

