#!/bin/sh

# --file-tags=yes   Same as --extra=+f  ?
# --extra=+g   Unsupported?

/sw/bin/ctags-exuberant --if0=yes --recurse --extra=+fq --fields=+i --c-kinds=+p --ruby-kinds=+cfFm --langmap=c:+.m . ../libnet

