.TH "libnet-headers.h" 3 "10 Mar 2004" "libnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libnet-headers.h \- libnet header information  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBlibnet_802_1q_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_802_1x_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_802_2_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_802_2snap_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_802_3_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ah_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_arp_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_as_lsa_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_auth_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_bgp4_header_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_bgp4_notification_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_bgp4_open_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_cdp_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_cdp_value_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_dbd_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_dhcpv4_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_dnsv4_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_esp_ftr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_esp_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ether_addr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ethernet_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_fddi_addr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_fddi_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_gre_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_gre_sre_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_icmpv4_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_icmpv6_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_igmp_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_in6_addr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ipv4_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ipv6_destopts_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ipv6_frag_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ipv6_hbhopts_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ipv6_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ipv6_routing_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_isl_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_lsa_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_lsr_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_lsu_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_mpls_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_net_lsa_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ntp_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ntp_hdr_l_fp\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ntp_hdr_s_fp\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ospf_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_ospf_hello_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_rip_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_rpc_call\fP"
.br
.ti -1c
.RI "struct \fBlibnet_rpc_call_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_rpc_call_tcp_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_rpc_opaque_auth\fP"
.br
.ti -1c
.RI "struct \fBlibnet_rtr_lsa_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_sebek_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_stp_conf_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_stp_tcn_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_sum_lsa_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_tcp_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_token_ring_addr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_token_ring_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_udp_hdr\fP"
.br
.ti -1c
.RI "struct \fBlibnet_vrrp_hdr\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLIBNET_802_1Q_H\fP   0x12"
.br
.ti -1c
.RI "#define \fBLIBNET_802_1X_H\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_802_2_H\fP   0x03"
.br
.ti -1c
.RI "#define \fBLIBNET_802_2SNAP_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_802_3_H\fP   0x0e"
.br
.ti -1c
.RI "#define \fBLIBNET_ARP_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_ARP_ETH_IP_H\fP   0x1c"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_HEADER_H\fP   0x13"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_OPEN_H\fP   0x0a"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_UPDATE_H\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_NOTIFICATION_H\fP   0x02"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCPV4_H\fP   0xf0"
.br
.ti -1c
.RI "#define \fBLIBNET_UDP_DNSV4_H\fP   0x0c"
.br
.ti -1c
.RI "#define \fBLIBNET_TCP_DNSV4_H\fP   0x0e"
.br
.ti -1c
.RI "#define \fBLIBNET_ETH_H\fP   0x0e"
.br
.ti -1c
.RI "#define \fBLIBNET_FDDI_H\fP   0x15"
.br
.ti -1c
.RI "#define \fBLIBNET_ICMPV4_H\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_ICMPV4_ECHO_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_ICMPV4_MASK_H\fP   0x0c"
.br
.ti -1c
.RI "#define \fBLIBNET_ICMPV4_UNREACH_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_ICMPV4_TIMXCEED_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_ICMPV4_REDIRECT_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_ICMPV4_TS_H\fP   0x14"
.br
.ti -1c
.RI "#define \fBLIBNET_ICMPV6_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_IGMP_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_IPV4_H\fP   0x14"
.br
.ti -1c
.RI "#define \fBLIBNET_IPV6_H\fP   0x28"
.br
.ti -1c
.RI "#define \fBLIBNET_IPV6_FRAG_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_IPV6_ROUTING_H\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_IPV6_DESTOPTS_H\fP   0x02"
.br
.ti -1c
.RI "#define \fBLIBNET_IPV6_HBHOPTS_H\fP   0x02"
.br
.ti -1c
.RI "#define \fBLIBNET_IPSEC_ESP_HDR_H\fP   0x0c"
.br
.ti -1c
.RI "#define \fBLIBNET_IPSEC_ESP_FTR_H\fP   0x02"
.br
.ti -1c
.RI "#define \fBLIBNET_IPSEC_AH_H\fP   0x10"
.br
.ti -1c
.RI "#define \fBLIBNET_ISL_H\fP   0x1a"
.br
.ti -1c
.RI "#define \fBLIBNET_GRE_H\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_GRE_SRE_H\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_MPLS_H\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_H\fP   0x10"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_HELLO_H\fP   0x18"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_DBD_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_LSR_H\fP   0x0c"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_LSU_H\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_LSA_H\fP   0x14"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_AUTH_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_CKSUM\fP   0x10"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_LS_RTR_H\fP   0x10"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_LS_NET_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_LS_SUM_H\fP   0x0c"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_LS_AS_EXT_H\fP   0x10"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_H\fP   0x30"
.br
.ti -1c
.RI "#define \fBLIBNET_RIP_H\fP   0x18"
.br
.ti -1c
.RI "#define \fBLIBNET_RPC_CALL_H\fP   0x28"
.br
.ti -1c
.RI "#define \fBLIBNET_RPC_CALL_TCP_H\fP   0x2c"
.br
.ti -1c
.RI "#define \fBLIBNET_SEBEK_H\fP   0x30"
.br
.ti -1c
.RI "#define \fBLIBNET_STP_CONF_H\fP   0x23"
.br
.ti -1c
.RI "#define \fBLIBNET_STP_TCN_H\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_TOKEN_RING_H\fP   0x16"
.br
.ti -1c
.RI "#define \fBLIBNET_TCP_H\fP   0x14"
.br
.ti -1c
.RI "#define \fBLIBNET_UDP_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_VRRP_H\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_802_1Q_PRIMASK\fP   0x0007"
.br
.ti -1c
.RI "#define \fBLIBNET_802_1Q_CFIMASK\fP   0x0001"
.br
.ti -1c
.RI "#define \fBLIBNET_802_1Q_VIDMASK\fP   0x0fff"
.br
.ti -1c
.RI "#define \fBLIBNET_802_1X_PACKET\fP   0x00"
.br
.ti -1c
.RI "#define \fBLIBNET_802_1X_START\fP   0x01"
.br
.ti -1c
.RI "#define \fBLIBNET_802_1X_LOGOFF\fP   0x02"
.br
.ti -1c
.RI "#define \fBLIBNET_802_1X_KEY\fP   0x03"
.br
.ti -1c
.RI "#define \fBLIBNET_802_1X_ENCASFAL\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_SAP_STP\fP   0x42"
.br
.ti -1c
.RI "#define \fBLIBNET_SAP_SNAP\fP   0xaa"
.br
.ti -1c
.RI "#define \fBARPHRD_NETROM\fP   0"
.br
.ti -1c
.RI "#define \fBARPHRD_ETHER\fP   1"
.br
.ti -1c
.RI "#define \fBARPHRD_EETHER\fP   2"
.br
.ti -1c
.RI "#define \fBARPHRD_AX25\fP   3"
.br
.ti -1c
.RI "#define \fBARPHRD_PRONET\fP   4"
.br
.ti -1c
.RI "#define \fBARPHRD_CHAOS\fP   5"
.br
.ti -1c
.RI "#define \fBARPHRD_IEEE802\fP   6"
.br
.ti -1c
.RI "#define \fBARPHRD_ARCNET\fP   7"
.br
.ti -1c
.RI "#define \fBARPHRD_APPLETLK\fP   8"
.br
.ti -1c
.RI "#define \fBARPHRD_LANSTAR\fP   9"
.br
.ti -1c
.RI "#define \fBARPHRD_DLCI\fP   15"
.br
.ti -1c
.RI "#define \fBARPHRD_ATM\fP   19"
.br
.ti -1c
.RI "#define \fBARPHRD_METRICOM\fP   23"
.br
.ti -1c
.RI "#define \fBARPHRD_IPSEC\fP   31"
.br
.ti -1c
.RI "#define \fBARPOP_REQUEST\fP   1"
.br
.ti -1c
.RI "#define \fBARPOP_REPLY\fP   2"
.br
.ti -1c
.RI "#define \fBARPOP_REVREQUEST\fP   3"
.br
.ti -1c
.RI "#define \fBARPOP_REVREPLY\fP   4"
.br
.ti -1c
.RI "#define \fBARPOP_INVREQUEST\fP   8"
.br
.ti -1c
.RI "#define \fBARPOP_INVREPLY\fP   9"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_MARKER_SIZE\fP   16"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_OPEN\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_UPDATE\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_NOTIFICATION\fP   3"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_KEEPALIVE\fP   4"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_MESSAGE_HEADER_ERROR\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_OPEN_MESSAGE_ERROR\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_UPDATE_MESSAGE_ERROR\fP   3"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_HOLD_TIMER_EXPIRED\fP   4"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_FINITE_STATE__ERROR\fP   5"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_CEASE\fP   6"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_CONNECTION_NOT_SYNCHRONIZED\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_BAD_MESSAGE_LENGTH\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_BAD_MESSAGE_TYPE\fP   3"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_UNSUPPORTED_VERSION_NUMBER\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_BAD_PEER_AS\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_BAD_BGP_IDENTIFIER\fP   3"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_UNSUPPORTED_OPTIONAL_PARAMETER\fP   4"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_AUTHENTICATION_FAILURE\fP   5"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_UNACCEPTABLE_HOLD_TIME\fP   6"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_MALFORMED_ATTRIBUTE_LIST\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_UNRECOGNIZED_WELL_KNOWN_ATTRIBUTE\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_MISSING_WELL_KNOWN_ATTRIBUTE\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_ATTRIBUTE_FLAGS_ERROR\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_ATTRIBUTE_LENGTH_ERROR\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_INVALID_ORIGIN_ATTRIBUTE\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_AS_ROUTING_LOOP\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_INVALID_NEXT_HOP_ATTRIBUTE\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_OPTIONAL_ATTRIBUTE_ERROR\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_INVALID_NETWORK_FIELD\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_BGP4_MALFORMED_AS_PATH\fP"
.br
.ti -1c
.RI "#define \fBLIBNET_PROTO_CDP\fP   200"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_DEVID\fP   0x1"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_ADDRESS\fP   0x2"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_PORTID\fP   0x3"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_CAPABIL\fP   0x4"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_VERSION\fP   0x5"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_PLATFORM\fP   0x6"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_IPPREFIX\fP   0x7"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_CAP_L3R\fP   0x01"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_CAP_L2B\fP   0x02"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_CAP_L2SRB\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_CAP_L2S\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_CAP_SR\fP   0x10"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_CAP_NOI\fP   0x20"
.br
.ti -1c
.RI "#define \fBLIBNET_CDP_CAP_L1F\fP   0x40"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_REQUEST\fP   0x1"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_REPLY\fP   0x2"
.br
.ti -1c
.RI "#define \fBDHCP_MAGIC\fP   0x63825363"
.br
.ti -1c
.RI "#define \fBLIBNET_BOOTP_MIN_LEN\fP   0x12c"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_PAD\fP   0x00"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_SUBNETMASK\fP   0x01"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_TIMEOFFSET\fP   0x02"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_ROUTER\fP   0x03"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_TIMESERVER\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NAMESERVER\fP   0x05"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_DNS\fP   0x06"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_LOGSERV\fP   0x07"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_COOKIESERV\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_LPRSERV\fP   0x09"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_IMPSERV\fP   0x0a"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_RESSERV\fP   0x0b"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_HOSTNAME\fP   0x0c"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_BOOTFILESIZE\fP   0x0d"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_DUMPFILE\fP   0x0e"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_DOMAINNAME\fP   0x0f"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_SWAPSERV\fP   0x10"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_ROOTPATH\fP   0x11"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_EXTENPATH\fP   0x12"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_IPFORWARD\fP   0x13"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_SRCROUTE\fP   0x14"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_POLICYFILTER\fP   0x15"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MAXASMSIZE\fP   0x16"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_IPTTL\fP   0x17"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MTUTIMEOUT\fP   0x18"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MTUTABLE\fP   0x19"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MTUSIZE\fP   0x1a"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_LOCALSUBNETS\fP   0x1b"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_BROADCASTADDR\fP   0x1c"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_DOMASKDISCOV\fP   0x1d"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MASKSUPPLY\fP   0x1e"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_DOROUTEDISC\fP   0x1f"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_ROUTERSOLICIT\fP   0x20"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_STATICROUTE\fP   0x21"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_TRAILERENCAP\fP   0x22"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_ARPTIMEOUT\fP   0x23"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_ETHERENCAP\fP   0x24"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_TCPTTL\fP   0x25"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_TCPKEEPALIVE\fP   0x26"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_TCPALIVEGARBAGE\fP   0x27"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NISDOMAIN\fP   0x28"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NISSERVERS\fP   0x29"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NISTIMESERV\fP   0x2a"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_VENDSPECIFIC\fP   0x2b"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NBNS\fP   0x2c"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NBDD\fP   0x2d"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NBTCPIP\fP   0x2e"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NBTCPSCOPE\fP   0x2f"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_XFONT\fP   0x30"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_XDISPLAYMGR\fP   0x31"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_DISCOVERADDR\fP   0x32"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_LEASETIME\fP   0x33"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_OPTIONOVERLOAD\fP   0x34"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MESSAGETYPE\fP   0x35"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_SERVIDENT\fP   0x36"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_PARAMREQUEST\fP   0x37"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MESSAGE\fP   0x38"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MAXMSGSIZE\fP   0x39"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_RENEWTIME\fP   0x3a"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_REBINDTIME\fP   0x3b"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_CLASSSID\fP   0x3c"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_CLIENTID\fP   0x3d"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NISPLUSDOMAIN\fP   0x40"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NISPLUSSERVERS\fP   0x41"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MOBILEIPAGENT\fP   0x44"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_SMTPSERVER\fP   0x45"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_POP3SERVER\fP   0x46"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_NNTPSERVER\fP   0x47"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_WWWSERVER\fP   0x48"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_FINGERSERVER\fP   0x49"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_IRCSERVER\fP   0x4a"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_STSERVER\fP   0x4b"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_STDASERVER\fP   0x4c"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_END\fP   0xff"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MSGDISCOVER\fP   0x01"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MSGOFFER\fP   0x02"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MSGREQUEST\fP   0x03"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MSGDECLINE\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MSGACK\fP   0x05"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MSGNACK\fP   0x06"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MSGRELEASE\fP   0x07"
.br
.ti -1c
.RI "#define \fBLIBNET_DHCP_MSGINFORM\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_DNS_H\fP   LIBNET_UDP_DNSV4_H"
.br
.ti -1c
.RI "#define \fBETHERTYPE_PUP\fP   0x0200"
.br
.ti -1c
.RI "#define \fBETHERTYPE_IP\fP   0x0800"
.br
.ti -1c
.RI "#define \fBETHERTYPE_ARP\fP   0x0806"
.br
.ti -1c
.RI "#define \fBETHERTYPE_REVARP\fP   0x8035"
.br
.ti -1c
.RI "#define \fBETHERTYPE_VLAN\fP   0x8100"
.br
.ti -1c
.RI "#define \fBETHERTYPE_EAP\fP   0x888e"
.br
.ti -1c
.RI "#define \fBETHERTYPE_MPLS\fP   0x8847"
.br
.ti -1c
.RI "#define \fBETHERTYPE_LOOPBACK\fP   0x9000"
.br
.ti -1c
.RI "#define \fBLIBNET_FDDI_LLC_FRAME\fP   0x10"
.br
.ti -1c
.RI "#define \fBLIBNET_FDDI_48BIT_ADDR\fP   0x40"
.br
.ti -1c
.RI "#define \fBLIBNET_FDDI_FC_REQD\fP   LIBNET_FDDI_LLC_FRAME | LIBNET_FDDI_48BIT_ADDR"
.br
.ti -1c
.RI "#define \fBFDDI_TYPE_IP\fP   0x0800"
.br
.ti -1c
.RI "#define \fBFDDI_TYPE_ARP\fP   0x0806"
.br
.ti -1c
.RI "#define \fBFDDI_TYPE_REVARP\fP   0x8035"
.br
.ti -1c
.RI "#define \fBGRE_CSUM\fP   0x8000"
.br
.ti -1c
.RI "#define \fBGRE_ROUTING\fP   0x4000"
.br
.ti -1c
.RI "#define \fBGRE_KEY\fP   0x2000"
.br
.ti -1c
.RI "#define \fBGRE_SEQ\fP   0x1000"
.br
.ti -1c
.RI "#define \fBGRE_STRICT\fP   0x0800"
.br
.ti -1c
.RI "#define \fBGRE_REC\fP   0x0700"
.br
.ti -1c
.RI "#define \fBGRE_ACK\fP   0x0080"
.br
.ti -1c
.RI "#define \fBGRE_FLAGS_MASK\fP   0x00F8"
.br
.ti -1c
.RI "#define \fBGRE_VERSION_MASK\fP   0x0007"
.br
.ti -1c
.RI "#define \fBGRE_VERSION_0\fP   0x0000"
.br
.ti -1c
.RI "#define \fBGRE_VERSION_1\fP   0x0001"
.br
.ti -1c
.RI "#define \fBGRE_SNA\fP   0x0004"
.br
.ti -1c
.RI "#define \fBGRE_OSI_NETWORK_LAYER\fP   0x00FE"
.br
.ti -1c
.RI "#define \fBGRE_PUP\fP   0x0200"
.br
.ti -1c
.RI "#define \fBGRE_XNS\fP   0x0600"
.br
.ti -1c
.RI "#define \fBGRE_IP\fP   0x0800"
.br
.ti -1c
.RI "#define \fBGRE_CHAOS\fP   0x0804"
.br
.ti -1c
.RI "#define \fBGRE_RFC_826_ARP\fP   0x0806"
.br
.ti -1c
.RI "#define \fBGRE_FRAME_RELAY_ARP\fP   0x0808"
.br
.ti -1c
.RI "#define \fBGRE_VINES\fP   0x0BAD"
.br
.ti -1c
.RI "#define \fBGRE_VINES_ECHO\fP   0x0BAE"
.br
.ti -1c
.RI "#define \fBGRE_VINES_LOOPBACK\fP   0x0BAF"
.br
.ti -1c
.RI "#define \fBGRE_DECNET\fP   0x6003"
.br
.ti -1c
.RI "#define \fBGRE_TRANSPARENT_ETHERNET_BRIDGING\fP   0x6558"
.br
.ti -1c
.RI "#define \fBGRE_RAW_FRAME_RELAY\fP   0x6559"
.br
.ti -1c
.RI "#define \fBGRE_APOLLO_DOMAIN\fP   0x8019"
.br
.ti -1c
.RI "#define \fBGRE_ETHERTALK\fP   0x809B"
.br
.ti -1c
.RI "#define \fBGRE_NOVELL_IPX\fP   0x8137"
.br
.ti -1c
.RI "#define \fBGRE_RFC_1144_TCP_IP_COMPRESSION\fP   0x876B"
.br
.ti -1c
.RI "#define \fBGRE_IP_AUTONOMOUS_SYSTEMS\fP   0x876C"
.br
.ti -1c
.RI "#define \fBGRE_SECURE_DATA\fP   0x876D"
.br
.ti -1c
.RI "#define \fBGRE_PPP\fP   0x880b"
.br
.ti -1c
.RI "#define \fBgre_sum\fP   _data._gre.sum"
.br
.ti -1c
.RI "#define \fBgre_offset\fP   _data._gre.offset"
.br
.ti -1c
.RI "#define \fBgre_key\fP   _data._gre.key"
.br
.ti -1c
.RI "#define \fBgre_seq\fP   _data._gre.seq"
.br
.ti -1c
.RI "#define \fBegre_payload_s\fP   _data._egre.payload_s"
.br
.ti -1c
.RI "#define \fBegre_callID\fP   _data._egre.callID"
.br
.ti -1c
.RI "#define \fBegre_seq\fP   _data._egre.seq"
.br
.ti -1c
.RI "#define \fBegre_ack\fP   _data._egre.ack"
.br
.ti -1c
.RI "#define \fBIPPROTO_GRE\fP   47"
.br
.ti -1c
.RI "#define \fBIPTOS_LOWDELAY\fP   0x10"
.br
.ti -1c
.RI "#define \fBIPTOS_THROUGHPUT\fP   0x08"
.br
.ti -1c
.RI "#define \fBIPTOS_RELIABILITY\fP   0x04"
.br
.ti -1c
.RI "#define \fBIPTOS_LOWCOST\fP   0x02"
.br
.ti -1c
.RI "#define \fBIP_RF\fP   0x8000"
.br
.ti -1c
.RI "#define \fBIP_DF\fP   0x4000"
.br
.ti -1c
.RI "#define \fBIP_MF\fP   0x2000"
.br
.ti -1c
.RI "#define \fBIP_OFFMASK\fP   0x1fff"
.br
.ti -1c
.RI "#define \fBIPOPT_EOL\fP   0"
.br
.ti -1c
.RI "#define \fBIPOPT_NOP\fP   1"
.br
.ti -1c
.RI "#define \fBIPOPT_RR\fP   7"
.br
.ti -1c
.RI "#define \fBIPOPT_TS\fP   68"
.br
.ti -1c
.RI "#define \fBIPOPT_SECURITY\fP   130"
.br
.ti -1c
.RI "#define \fBIPOPT_LSRR\fP   131"
.br
.ti -1c
.RI "#define \fBIPOPT_SATID\fP   136"
.br
.ti -1c
.RI "#define \fBIPOPT_SSRR\fP   137"
.br
.ti -1c
.RI "#define \fBlibnet_s6_addr\fP   __u6_addr.__u6_addr8"
.br
.ti -1c
.RI "#define \fBLIBNET_IPV6_NH_FRAGMENT\fP   44"
.br
.ti -1c
.RI "#define \fBLIBNET_IPV6_NH_ROUTING\fP   43"
.br
.ti -1c
.RI "#define \fBLIBNET_IPV6_NH_DESTOPTS\fP   60"
.br
.ti -1c
.RI "#define \fBLIBNET_IPV6_NH_HBH\fP   0"
.br
.ti -1c
.RI "#define \fBIPPROTO_ICMP6\fP   0x3a"
.br
.ti -1c
.RI "#define \fBICMP6_ECHO\fP   128"
.br
.ti -1c
.RI "#define \fBICMP6_ECHOREPLY\fP   129"
.br
.ti -1c
.RI "#define \fBICMP6_UNREACH\fP   1"
.br
.ti -1c
.RI "#define \fBICMP6_PKTTOOBIG\fP   2"
.br
.ti -1c
.RI "#define \fBICMP6_TIMXCEED\fP   3"
.br
.ti -1c
.RI "#define \fBICMP6_PARAMPROB\fP   4"
.br
.ti -1c
.RI "#define \fBICMP_ECHOREPLY\fP   0"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH\fP   3"
.br
.ti -1c
.RI "#define \fBICMP_SOURCEQUENCH\fP   4"
.br
.ti -1c
.RI "#define \fBICMP_REDIRECT\fP   5"
.br
.ti -1c
.RI "#define \fBICMP_ECHO\fP   8"
.br
.ti -1c
.RI "#define \fBICMP_ROUTERADVERT\fP   9"
.br
.ti -1c
.RI "#define \fBICMP_ROUTERSOLICIT\fP   10"
.br
.ti -1c
.RI "#define \fBICMP_TIMXCEED\fP   11"
.br
.ti -1c
.RI "#define \fBICMP_PARAMPROB\fP   12"
.br
.ti -1c
.RI "#define \fBICMP_TSTAMP\fP   13"
.br
.ti -1c
.RI "#define \fBICMP_TSTAMPREPLY\fP   14"
.br
.ti -1c
.RI "#define \fBICMP_IREQ\fP   15"
.br
.ti -1c
.RI "#define \fBICMP_IREQREPLY\fP   16"
.br
.ti -1c
.RI "#define \fBICMP_MASKREQ\fP   17"
.br
.ti -1c
.RI "#define \fBICMP_MASKREPLY\fP   18"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_NET\fP   0"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_HOST\fP   1"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_PROTOCOL\fP   2"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_PORT\fP   3"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_NEEDFRAG\fP   4"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_SRCFAIL\fP   5"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_NET_UNKNOWN\fP   6"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_HOST_UNKNOWN\fP   7"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_ISOLATED\fP   8"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_NET_PROHIB\fP   9"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_HOST_PROHIB\fP   10"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_TOSNET\fP   11"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_TOSHOST\fP   12"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_FILTER_PROHIB\fP   13"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_HOST_PRECEDENCE\fP   14"
.br
.ti -1c
.RI "#define \fBICMP_UNREACH_PRECEDENCE_CUTOFF\fP   15"
.br
.ti -1c
.RI "#define \fBICMP_REDIRECT_NET\fP   0"
.br
.ti -1c
.RI "#define \fBICMP_REDIRECT_HOST\fP   1"
.br
.ti -1c
.RI "#define \fBICMP_REDIRECT_TOSNET\fP   2"
.br
.ti -1c
.RI "#define \fBICMP_REDIRECT_TOSHOST\fP   3"
.br
.ti -1c
.RI "#define \fBICMP_TIMXCEED_INTRANS\fP   0"
.br
.ti -1c
.RI "#define \fBICMP_TIMXCEED_REASS\fP   1"
.br
.ti -1c
.RI "#define \fBICMP_PARAMPROB_OPTABSENT\fP   1"
.br
.ti -1c
.RI "#define \fBicmp_id\fP   hun.echo.id"
.br
.ti -1c
.RI "#define \fBicmp_seq\fP   hun.echo.seq"
.br
.ti -1c
.RI "#define \fBicmp_mask\fP   dun.mask"
.br
.ti -1c
.RI "#define \fBicmp_data\fP   dun.data"
.br
.ti -1c
.RI "#define \fBicmp_otime\fP   dun.ts.its_otime"
.br
.ti -1c
.RI "#define \fBicmp_rtime\fP   dun.ts.its_rtime"
.br
.ti -1c
.RI "#define \fBicmp_ttime\fP   dun.ts.its_ttime"
.br
.ti -1c
.RI "#define \fBIGMP_MEMBERSHIP_QUERY\fP   0x11"
.br
.ti -1c
.RI "#define \fBIGMP_V1_MEMBERSHIP_REPORT\fP   0x12"
.br
.ti -1c
.RI "#define \fBIGMP_V2_MEMBERSHIP_REPORT\fP   0x16"
.br
.ti -1c
.RI "#define \fBIGMP_LEAVE_GROUP\fP   0x17"
.br
.ti -1c
.RI "#define \fBIPPROTO_ESP\fP   50"
.br
.ti -1c
.RI "#define \fBIPPROTO_AH\fP   51"
.br
.ti -1c
.RI "#define \fBLIBNET_PROTO_ISL\fP   201"
.br
.ti -1c
.RI "#define \fBIPPROTO_OSPF\fP   89"
.br
.ti -1c
.RI "#define \fBIPPROTO_OSPF_LSA\fP   890"
.br
.ti -1c
.RI "#define \fBLIBNET_MODX\fP   4102"
.br
.ti -1c
.RI "#define \fBLIBNET_OPT_EBIT\fP   0x02"
.br
.ti -1c
.RI "#define \fBLIBNET_OPT_MCBIT\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_OPT_NPBIT\fP   0x08"
.br
.ti -1c
.RI "#define \fBLIBNET_OPT_EABIT\fP   0x10"
.br
.ti -1c
.RI "#define \fBLIBNET_OPT_DCBIT\fP   0x20"
.br
.ti -1c
.RI "#define \fBLIBNET_MPLS_BOS_ON\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_MPLS_BOS_OFF\fP   0"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_LI_NW\fP   0x0"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_LI_AS\fP   0x1"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_LI_DS\fP   0x2"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_LI_AC\fP   0x3"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_VN_2\fP   0x2"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_VN_3\fP   0x3"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_VN_4\fP   0x4"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_MODE_R\fP   0x0"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_MODE_A\fP   0x1"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_MODE_P\fP   0x2"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_MODE_C\fP   0x3"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_MODE_S\fP   0x4"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_MODE_B\fP   0x5"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_MODE_RC\fP   0x6"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_MODE_RP\fP   0x7"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_STRATUM_UNAVAIL\fP   0x0"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_STRATUM_PRIMARY\fP   0x1"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_LOCAL\fP   0x4c4f434c"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_PPS\fP   0x50505300"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_ACTS\fP   0x41435453"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_USNO\fP   0x55534e4f"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_PTB\fP   0x50544200"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_TDF\fP   0x54444600"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_DCF\fP   0x44434600"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_MSF\fP   0x4d534600"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_WWV\fP   0x57575600"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_WWVB\fP   0x57575642"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_WWVH\fP   0x57575648"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_CHU\fP   0x43485500"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_LORC\fP   0x4c4f5243"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_OMEG\fP   0x4f4d4547"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_GPS\fP   0x47505300"
.br
.ti -1c
.RI "#define \fBLIBNET_NTP_REF_GOES\fP   0x474f4553"
.br
.ti -1c
.RI "#define \fBOSPFVERSION\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_UMD\fP   0"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_HELLO\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_DBD\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_LSR\fP   3"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_LSU\fP   4"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_LSA\fP   5"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_AUTH_NULL\fP   0"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_AUTH_SIMPLE\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_OSPF_AUTH_MD5\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_DBD_IBI\fP   0x01"
.br
.ti -1c
.RI "#define \fBLIBNET_DBD_MBIT\fP   0x02"
.br
.ti -1c
.RI "#define \fBLIBNET_DBD_MSBIT\fP   0x04"
.br
.ti -1c
.RI "#define \fBLIBNET_LS_TYPE_RTR\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_LS_TYPE_NET\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_LS_TYPE_IP\fP   3"
.br
.ti -1c
.RI "#define \fBLIBNET_LS_TYPE_ASBR\fP   4"
.br
.ti -1c
.RI "#define \fBLIBNET_LS_TYPE_ASEXT\fP   5"
.br
.ti -1c
.RI "#define \fBLIBNET_RTR_FLAGS_W\fP   0x0100"
.br
.ti -1c
.RI "#define \fBLIBNET_RTR_FLAGS_E\fP   0x0200"
.br
.ti -1c
.RI "#define \fBLIBNET_RTR_FLAGS_B\fP   0x0400"
.br
.ti -1c
.RI "#define \fBLIBNET_LINK_ID_NBR_ID\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_LINK_ID_IP_DES\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_LINK_ID_SUB\fP   3"
.br
.ti -1c
.RI "#define \fBLIBNET_RTR_TYPE_PTP\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_RTR_TYPE_TRANS\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_RTR_TYPE_STUB\fP   3"
.br
.ti -1c
.RI "#define \fBRTR_TYPE_VRTL\fP   4"
.br
.ti -1c
.RI "#define \fBLIBNET_AS_E_BIT_ON\fP   0x80000000"
.br
.ti -1c
.RI "#define \fBRIPCMD_REQUEST\fP   1"
.br
.ti -1c
.RI "#define \fBRIPCMD_RESPONSE\fP   2"
.br
.ti -1c
.RI "#define \fBRIPCMD_TRACEON\fP   3"
.br
.ti -1c
.RI "#define \fBRIPCMD_TRACEOFF\fP   4"
.br
.ti -1c
.RI "#define \fBRIPCMD_POLL\fP   5"
.br
.ti -1c
.RI "#define \fBRIPCMD_POLLENTRY\fP   6"
.br
.ti -1c
.RI "#define \fBRIPCMD_MAX\fP   7"
.br
.ti -1c
.RI "#define \fBRIPVER_0\fP   0"
.br
.ti -1c
.RI "#define \fBRIPVER_1\fP   1"
.br
.ti -1c
.RI "#define \fBRIPVER_2\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_RPC_CALL\fP   0"
.br
.ti -1c
.RI "#define \fBLIBNET_RPC_REPLY\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_RPC_VERS\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_RPC_LAST_FRAG\fP   0x80000000"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROGRAM\fP   100000"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_NULL\fP   0"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_SET\fP   1"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_UNSET\fP   2"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_GETADDR\fP   3"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_DUMP\fP   4"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_CALLIT\fP   5"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_BCAST\fP   5"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_GETTIME\fP   6"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_UADDR2TADDR\fP   7"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_TADDR2UADDR\fP   8"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_GETVERSADDR\fP   9"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_INDIRECT\fP   10"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_GETADDRLIST\fP   11"
.br
.ti -1c
.RI "#define \fBLIBNET_PMAP_PROC_GETSTAT\fP   12"
.br
.ti -1c
.RI "#define \fBTH_FIN\fP   0x01"
.br
.ti -1c
.RI "#define \fBTH_SYN\fP   0x02"
.br
.ti -1c
.RI "#define \fBTH_RST\fP   0x04"
.br
.ti -1c
.RI "#define \fBTH_PUSH\fP   0x08"
.br
.ti -1c
.RI "#define \fBTH_ACK\fP   0x10"
.br
.ti -1c
.RI "#define \fBTH_URG\fP   0x20"
.br
.ti -1c
.RI "#define \fBTH_ECE\fP   0x40"
.br
.ti -1c
.RI "#define \fBTH_CWR\fP   0x80"
.br
.ti -1c
.RI "#define \fBLIBNET_TOKEN_RING_FRAME\fP   0x10"
.br
.ti -1c
.RI "#define \fBLIBNET_TOKEN_RING_LLC_FRAME\fP   0x40"
.br
.ti -1c
.RI "#define \fBTOKEN_RING_TYPE_IP\fP   0x0800"
.br
.ti -1c
.RI "#define \fBTOKEN_RING_TYPE_ARP\fP   0x0806"
.br
.ti -1c
.RI "#define \fBTOKEN_RING_TYPE_REVARP\fP   0x8035"
.br
.ti -1c
.RI "#define \fBSEBEK_PROTO_VERSION\fP   1"
.br
.ti -1c
.RI "#define \fBSEBEK_TYPE_READ\fP   0"
.br
.ti -1c
.RI "#define \fBSEBEK_TYPE_WRITE\fP   1"
.br
.ti -1c
.RI "#define \fBSEBEK_CMD_LENGTH\fP   12"
.br
.ti -1c
.RI "#define \fBIPPROTO_VRRP\fP   112"
.br
.ti -1c
.RI "#define \fBLIBNET_VRRP_VERSION_01\fP   0x1"
.br
.ti -1c
.RI "#define \fBLIBNET_VRRP_VERSION_02\fP   0x2"
.br
.ti -1c
.RI "#define \fBLIBNET_VRRP_TYPE_ADVERT\fP   0x1"
.br
.ti -1c
.RI "#define \fBLIBNET_VRRP_AUTH_NONE\fP   0x1"
.br
.ti -1c
.RI "#define \fBLIBNET_VRRP_AUTH_PASSWD\fP   0x2"
.br
.ti -1c
.RI "#define \fBLIBNET_VRRP_AUTH_IPAH\fP   0x3"
.br
.in -1c
.SH "Detailed Description"
.PP 
libnet header information 


.SH "Define Documentation"
.PP 
.SS "#define LIBNET_802_1Q_CFIMASK   0x0001"
.PP
CFI mask 
.SS "#define LIBNET_802_1Q_H   0x12"
.PP
802.1Q header: 18 bytes 
.SS "#define LIBNET_802_1Q_PRIMASK   0x0007"
.PP
priority mask 
.SS "#define LIBNET_802_1Q_VIDMASK   0x0fff"
.PP
vid mask 
.SS "#define LIBNET_802_1X_ENCASFAL   0x04"
.PP
802.1x encasfal 
.SS "#define LIBNET_802_1X_H   0x04"
.PP
802.1X header: 4 bytes 
.SS "#define LIBNET_802_1X_KEY   0x03"
.PP
802.1x key 
.SS "#define LIBNET_802_1X_LOGOFF   0x02"
.PP
802.1x logoff 
.SS "#define LIBNET_802_1X_PACKET   0x00"
.PP
802.1x packet 
.SS "#define LIBNET_802_1X_START   0x01"
.PP
802.1x start 
.SS "#define LIBNET_802_2_H   0x03"
.PP
802.2 LLC header: 3 bytes 
.SS "#define LIBNET_802_2SNAP_H   0x08"
.PP
802.2 LLC/SNAP header:8 bytes 
.SS "#define LIBNET_802_3_H   0x0e"
.PP
802.3 header: 14 bytes 
.SS "#define LIBNET_ARP_ETH_IP_H   0x1c"
.PP
ARP w/ ETH and IP: 28 bytes 
.SS "#define LIBNET_ARP_H   0x08"
.PP
ARP header w/o addrs: 8 bytes 
.SS "#define LIBNET_BGP4_HEADER_H   0x13"
.PP
BGP header: 19 bytes 
.SS "#define LIBNET_BGP4_NOTIFICATION_H   0x02"
.PP
BGP notif. header: 2 bytes 
.SS "#define LIBNET_BGP4_OPEN_H   0x0a"
.PP
BGP open header: 10 bytes 
.SS "#define LIBNET_BGP4_UPDATE_H   0x04"
.PP
BGP open header: 4 bytes 
.SS "#define LIBNET_CDP_H   0x08"
.PP
CDP header base: 8 bytes 
.SS "#define LIBNET_DHCPV4_H   0xf0"
.PP
DHCP v4 header: 240 bytes 
.SS "#define LIBNET_ETH_H   0x0e"
.PP
Ethernet header: 14 bytes 
.SS "#define LIBNET_FDDI_H   0x15"
.PP
FDDI header: 21 bytes 
.SS "#define LIBNET_GRE_H   0x04"
.PP
GRE header: 4 bytes 
.SS "#define LIBNET_GRE_SRE_H   0x04"
.PP
GRE SRE header: 4 bytes 
.SS "#define LIBNET_ICMPV4_ECHO_H   0x08"
.PP
ICMP_ECHO header: 8 bytes 
.SS "#define LIBNET_ICMPV4_H   0x04"
.PP
ICMP header base: 4 bytes 
.SS "#define LIBNET_ICMPV4_MASK_H   0x0c"
.PP
ICMP_MASK header: 12 bytes 
.SS "#define LIBNET_ICMPV4_REDIRECT_H   0x08"
.PP
ICMP_REDIRECT header: 8 bytes 
.SS "#define LIBNET_ICMPV4_TIMXCEED_H   0x08"
.PP
ICMP_TIMXCEED header: 8 bytes 
.SS "#define LIBNET_ICMPV4_TS_H   0x14"
.PP
ICMP_TIMESTAMP headr:20 bytes 
.SS "#define LIBNET_ICMPV4_UNREACH_H   0x08"
.PP
ICMP_UNREACH header: 8 bytes 
.SS "#define LIBNET_ICMPV6_H   0x08"
.PP
ICMP6 header base: 8 bytes 
.SS "#define LIBNET_IGMP_H   0x08"
.PP
IGMP header: 8 bytes 
.SS "#define LIBNET_IPSEC_AH_H   0x10"
.PP
IPSEC AH header: 16 bytes 
.SS "#define LIBNET_IPSEC_ESP_FTR_H   0x02"
.PP
IPSEC ESP footer: 2 bytes 
.SS "#define LIBNET_IPSEC_ESP_HDR_H   0x0c"
.PP
IPSEC ESP header: 12 bytes 
.SS "#define LIBNET_IPV4_H   0x14"
.PP
IPv4 header: 20 bytes 
.SS "#define LIBNET_IPV6_DESTOPTS_H   0x02"
.PP
IPv6 dest opts base: 2 bytes 
.SS "#define LIBNET_IPV6_FRAG_H   0x08"
.PP
IPv6 frag header: 8 bytes 
.SS "#define LIBNET_IPV6_H   0x28"
.PP
IPv6 header: 40 bytes 
.SS "#define LIBNET_IPV6_HBHOPTS_H   0x02"
.PP
IPv6 hop/hop opt base:2 bytes 
.SS "#define LIBNET_IPV6_ROUTING_H   0x04"
.PP
IPv6 frag header base:4 bytes 
.SS "#define LIBNET_ISL_H   0x1a"
.PP
ISL header: 26 bytes 
.SS "#define LIBNET_MPLS_H   0x04"
.PP
MPLS header: 4 bytes 
.SS "#define LIBNET_NTP_H   0x30"
.PP
NTP header: 48 bytes 
.SS "#define LIBNET_OSPF_AUTH_H   0x08"
.PP
OSPF AUTH header: 8 bytes 
.SS "#define LIBNET_OSPF_CKSUM   0x10"
.PP
OSPF CKSUM header: 16 bytes 
.SS "#define LIBNET_OSPF_DBD_H   0x08"
.PP
OSPF DBD header: 8 bytes 
.SS "#define LIBNET_OSPF_H   0x10"
.PP
OSPF header: 16 bytes 
.SS "#define LIBNET_OSPF_HELLO_H   0x18"
.PP
OSPF hello header: 24 bytes 
.SS "#define LIBNET_OSPF_LS_AS_EXT_H   0x10"
.PP
OSPF LS AS header: 16 bytes 
.SS "#define LIBNET_OSPF_LS_NET_H   0x08"
.PP
OSPF LS NET header: 8 bytes 
.SS "#define LIBNET_OSPF_LS_RTR_H   0x10"
.PP
OSPF LS RTR header: 16 bytes 
.SS "#define LIBNET_OSPF_LS_SUM_H   0x0c"
.PP
OSPF LS SUM header: 12 bytes 
.SS "#define LIBNET_OSPF_LSA_H   0x14"
.PP
OSPF LSA header: 20 bytes 
.SS "#define LIBNET_OSPF_LSR_H   0x0c"
.PP
OSPF LSR header: 12 bytes 
.SS "#define LIBNET_OSPF_LSU_H   0x04"
.PP
OSPF LSU header: 4 bytes 
.SS "#define LIBNET_RIP_H   0x18"
.PP
RIP header base: 24 bytes 
.SS "#define LIBNET_RPC_CALL_H   0x28"
.PP
RPC header: 40 bytes (assuming 8 byte auth header) 
.SS "#define LIBNET_RPC_CALL_TCP_H   0x2c"
.PP
RPC header: 44 bytes (with record marking) 
.SS "#define LIBNET_STP_CONF_H   0x23"
.PP
STP conf header: 35 bytes 
.SS "#define LIBNET_STP_TCN_H   0x04"
.PP
STP tcn header: 4 bytes 
.SS "#define LIBNET_TCP_DNSV4_H   0x0e"
.PP
TCP DNS v4 header: 14 bytes 
.SS "#define LIBNET_TCP_H   0x14"
.PP
TCP header: 20 bytes 
.SS "#define LIBNET_TOKEN_RING_H   0x16"
.PP
Token Ring header: 22 bytes 
.SS "#define LIBNET_UDP_DNSV4_H   0x0c"
.PP
UDP DNS v4 header: 12 bytes 
.SS "#define LIBNET_UDP_H   0x08"
.PP
UDP header: 8 bytes 
.SS "#define LIBNET_VRRP_H   0x08"
.PP
VRRP header: 8 bytes 
.SH "Author"
.PP 
Generated automatically by Doxygen for libnet from the source code.
