.TH "libnet_802_1q_hdr" 3 "10 Mar 2004" "libnet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libnet_802_1q_hdr \- IEEE 802.1Q VLAN header
.SH SYNOPSIS
.br
.PP
\fC#include <libnet-headers.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u_int8_t \fBvlan_dhost\fP [ETHER_ADDR_LEN]"
.br
.ti -1c
.RI "u_int8_t \fBvlan_shost\fP [ETHER_ADDR_LEN]"
.br
.ti -1c
.RI "u_int16_t \fBvlan_tpi\fP"
.br
.ti -1c
.RI "u_int16_t \fBvlan_priority_c_vid\fP"
.br
.ti -1c
.RI "u_int16_t \fBvlan_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
IEEE 802.1Q (Virtual Local Area Network) VLAN header, static header size: 18 bytes 
.SH "Field Documentation"
.PP 
.SS "u_int8_t \fBlibnet_802_1q_hdr::vlan_dhost\fP[ETHER_ADDR_LEN]"
.PP
destination ethernet address 
.SS "u_int16_t \fBlibnet_802_1q_hdr::vlan_len\fP"
.PP
length or type (802.3 / Eth 2) 
.SS "u_int16_t \fBlibnet_802_1q_hdr::vlan_priority_c_vid\fP"
.PP
priority | VLAN ID 
.SS "u_int8_t \fBlibnet_802_1q_hdr::vlan_shost\fP[ETHER_ADDR_LEN]"
.PP
source ethernet address 
.SS "u_int16_t \fBlibnet_802_1q_hdr::vlan_tpi\fP"
.PP
tag protocol ID 

.SH "Author"
.PP 
Generated automatically by Doxygen for libnet from the source code.
